// Code generated by protoc-gen-validate
// source: api/v1/api.proto
// DO NOT EDIT!!!

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Passenger with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Passenger) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 3 {
		return PassengerValidationError{
			field:  "Name",
			reason: "value length must be at least 3 runes",
		}
	}

	return nil
}

// PassengerValidationError is the validation error returned by
// Passenger.Validate if the designated constraints aren't met.
type PassengerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PassengerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PassengerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PassengerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PassengerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PassengerValidationError) ErrorName() string { return "PassengerValidationError" }

// Error satisfies the builtin error interface
func (e PassengerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPassenger.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PassengerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PassengerValidationError{}

// Validate checks the field values on JumpRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *JumpRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetTo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JumpRequestValidationError{
				field:  "To",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := len(m.GetPassenger()); l < 2 || l > 5 {
		return JumpRequestValidationError{
			field:  "Passenger",
			reason: "value must contain between 2 and 5 items, inclusive",
		}
	}

	for idx, item := range m.GetPassenger() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JumpRequestValidationError{
					field:  fmt.Sprintf("Passenger[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// JumpRequestValidationError is the validation error returned by
// JumpRequest.Validate if the designated constraints aren't met.
type JumpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JumpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JumpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JumpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JumpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JumpRequestValidationError) ErrorName() string { return "JumpRequestValidationError" }

// Error satisfies the builtin error interface
func (e JumpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJumpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JumpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JumpRequestValidationError{}
